version: "3"

services:
  convifai_backend:
    image: luckulke/convifai_backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/backend-secrets-test.env

  convifai_frontend:
    image: convifai_frontend_test:1.0
    ports:
      - "5173:80"
  convifai_ctms:
    image: luckulke/convifai_ctms:latest
