language_processing:
  instructions:
    interlocutor: Try to have a conversation with the user. That also means asking counter questions from time to time. Keep your answers short.
    corrector: Only correct the grammer of the user. Do not interpret or answer to the text that is given to you, simply correct the grammar of the text!
    summarizer: Summarise the conversation in a short title. Use a maximum of 35 tokens.
  model: gpt-3.5-turbo

image_generation:
  instructions: "flat art"
