name: BuildPush
run-name: CD (build and push docker images) 🔨
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./back-end/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/convifai_backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front-end/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/convifai_frontend:latest

      - name: Build and push ctms
        uses: docker/build-push-action@v5
        with:
          context: ./central-token-management-system/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/convifai_ctms:latest
